version: "3.7"

services:

  mysql_db:
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - project_data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']

  spring_backend:
    image: tuankiet091002/socialpedia_backend:latest
    restart: on-failure
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    ports:
      - "80:80"
    depends_on:
      mysql_db:
        condition: service_started

  react_frontend:
    image: tuankiet091002/socialpedia_frontend:latest
    restart: on-failure
    ports:
      - "3000:80"
    depends_on:
      - spring_backend


volumes:
  project_data: