version: "3.7"

services:

  mysql_db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: kiet
      MYSQL_PASSWORD: 091002
      MYSQL_DATABASE: socialpedia
    volumes:
      - project_data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']

  redis_cache:
    image: redis:alpine
    network_mode: host
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    ports:
      - "6379:6379"

  spring_backend:
    image: tuankiet091002/socialpedia_backend:latest
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/socialpedia
      SPRING_DATASOURCE_USERNAME: kiet
      SPRING_DATASOURCE_PASSWORD: 091002
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_REDIS_HOST: localhost
      SPRING_REDIS_PORT: 6379
    ports:
      - "80:80"
    depends_on:
      mysql_db:
        condition: service_started
      redis_cache:
        condition: service_started

  react_frontend:
    image: tuankiet091002/socialpedia_frontend:latest
    restart: on-failure
    ports:
      - "3000:80"
    depends_on:
      - spring_backend


volumes:
  project_data: